// One-off migration: Neon Postgres -> Cloudflare D1 (SQLite) seed.sql
//
// Usage:
//   npm install pg
//   NEON_CONNECTION_STRING="postgresql://...pooler.../neondb?sslmode=require" node export_from_neon.mjs
//
// Get the connection string from the Neon console (splintmanager project ->
// Connect), or via the Neon MCP get_connection_string tool. Use a plain
// Postgres role connection string here, NOT the Neon Auth / Data API URL.
//
// Output: ./seed.sql — apply with:
//   wrangler d1 execute splint --remote --file=./seed.sql

import pg from 'pg';
import { writeFileSync } from 'fs';

const { Client } = pg;
const conn = process.env.NEON_CONNECTION_STRING;
if (!conn) {
  console.error('Set NEON_CONNECTION_STRING first.');
  process.exit(1);
}

const client = new Client({ connectionString: conn });
await client.connect();

function esc(v) {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return String(v);
  if (v instanceof Date) return `'${v.toISOString().slice(0, 10)}'`;
  return `'${String(v).replace(/'/g, "''")}'`;
}

async function dumpTable(table, columns, chunkSize = 10) {
  const { rows } = await client.query(`SELECT ${columns.join(',')} FROM ${table} ORDER BY 1`);
  if (!rows.length) return `-- ${table}: no rows\n`;
  let out = '';
  for (let i = 0; i < rows.length; i += chunkSize) {
    const chunk = rows.slice(i, i + chunkSize);
    const values = chunk.map(r => '(' + columns.map(c => esc(r[c])).join(',') + ')').join(',\n');
    out += `INSERT INTO ${table} (${columns.join(',')}) VALUES\n${values};\n`;
  }
  return out;
}

const masterCols = ['asset_id','asset_name','asset_category','asset_subcategory','asset_category_old','notes','release_date','min_horizon','max_horizon','eroi'];
const priceCols  = ['id','asset_id','asset_name','month','price_date','price','currency'];
const txCols     = ['transaction_id','transaction_type','asset_id','transaction_date','money_amount','money_currency','price_per_splint','price_currency','fees','fees_currency','confirmation_doc','day1_profit','fx_rate'];

let out = '-- Auto-generated by export_from_neon.mjs — data seed for D1\nPRAGMA defer_foreign_keys=TRUE;\n\n';
out += await dumpTable('splint_masterdata', masterCols) + '\n';
out += await dumpTable('splint_prices', priceCols) + '\n';
out += await dumpTable('splint_transactions', txCols) + '\n';

writeFileSync('./seed.sql', out, 'utf-8');
console.log('Wrote seed.sql (' + out.length + ' bytes).');

await client.end();
